// sys-dipu/Diseño/src/pages/auth/Login.tsx
import React, { useState } from 'react';
import { Role, Category } from '../../types';

export default function Login({ onLogin }: { onLogin: (role: Role, category?: Category) => void }) {
  const [tecnicoCategory, setTecnicoCategory] = useState<Category>('iniciativas');

  return (
    <div className="bg-surface text-on-surface min-h-screen flex flex-col items-center justify-center p-6 selection:bg-primary-container selection:text-on-primary-container relative overflow-hidden">
      {/* Decorative Element (Architectural Curator) */}
      <div className="absolute top-0 right-0 p-12 pointer-events-none opacity-20 hidden lg:block">
        <div className="w-64 h-64 border-[40px] border-surface-container-highest rounded-full"></div>
      </div>
      <div className="absolute bottom-0 left-0 p-12 pointer-events-none opacity-20 hidden lg:block">
        <div className="w-32 h-32 bg-surface-container-highest rounded-full"></div>
      </div>

      <main className="w-full max-w-md relative z-10">
        {/* Logo Section */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center mb-6">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary to-primary-dim flex items-center justify-center shadow-lg shadow-on-surface/5">
              <span className="material-symbols-outlined text-white text-2xl">account_balance</span>
            </div>
          </div>
          <h1 className="text-3xl font-extrabold text-on-surface tracking-tight mb-2 font-headline">
            Civic Ethos Suite
          </h1>
          <p className="text-on-surface-variant font-medium tracking-wide text-sm uppercase">
            Portal de Gestión Institucional
          </p>
        </div>

        {/* Login Card */}
        <div className="bg-surface-container-lowest p-10 rounded-2xl shadow-[0_12px_40px_rgba(43,52,55,0.06)] border border-outline-variant/10">
          <div className="mb-8">
            <h2 className="text-xl font-bold text-on-surface mb-1 font-headline">Acceso Administrativo</h2>
            <p className="text-on-surface-variant text-sm">Ingrese sus credenciales para continuar.</p>
          </div>
          <form className="space-y-6" onSubmit={(e) => { e.preventDefault(); onLogin('superadmin'); }}>
            {/* Username Field */}
            <div className="space-y-2">
              <label className="block text-xs font-semibold text-on-surface-variant uppercase tracking-widest" htmlFor="username">
                Usuario
              </label>
              <div className="relative group">
                <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none text-outline">
                  <span className="material-symbols-outlined text-sm">person</span>
                </div>
                <input
                  id="username"
                  name="username"
                  type="text"
                  required
                  placeholder="nombre.usuario"
                  className="block w-full pl-11 pr-4 py-3.5 bg-surface-container-low border-0 border-b-2 border-transparent focus:border-primary focus:ring-0 rounded-lg text-on-surface transition-all duration-300 placeholder:text-outline-variant/60"
                />
              </div>
            </div>

            {/* Password Field */}
            <div className="space-y-2">
              <div className="flex justify-between items-end">
                <label className="block text-xs font-semibold text-on-surface-variant uppercase tracking-widest" htmlFor="password">
                  Contraseña
                </label>
                <a href="#" className="text-xs font-medium text-primary hover:text-primary-dim transition-colors">¿Olvidó su clave?</a>
              </div>
              <div className="relative group">
                <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none text-outline">
                  <span className="material-symbols-outlined text-sm">lock</span>
                </div>
                <input
                  id="password"
                  name="password"
                  type="password"
                  required
                  placeholder="••••••••••••"
                  className="block w-full pl-11 pr-4 py-3.5 bg-surface-container-low border-0 border-b-2 border-transparent focus:border-primary focus:ring-0 rounded-lg text-on-surface transition-all duration-300 placeholder:text-outline-variant/60"
                />
              </div>
            </div>

            {/* Remember Me */}
            <div className="flex items-center space-x-2 px-1">
              <input type="checkbox" id="remember" className="w-4 h-4 rounded border-outline-variant text-primary focus:ring-primary/20 bg-surface-container" />
              <label htmlFor="remember" className="text-sm text-on-surface-variant cursor-pointer select-none">Recordar mi sesión</label>
            </div>

            {/* Submit Button */}
            <button type="submit" className="w-full py-4 px-6 bg-gradient-to-r from-primary to-primary-dim text-white font-bold rounded-xl shadow-md hover:shadow-xl hover:shadow-primary/20 transition-all duration-300 active:scale-[0.98] flex items-center justify-center space-x-2">
              <span>Entrar</span>
              <span className="material-symbols-outlined text-lg">arrow_forward</span>
            </button>
          </form>
        </div>

        {/* Test Buttons */}
        <div className="mt-8 bg-surface-container-lowest p-6 rounded-2xl border border-outline-variant/10 shadow-sm">
          <h3 className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest mb-4 text-center">Ingreso Rápido (Pruebas)</h3>
          <div className="grid grid-cols-1 gap-3">
            <button onClick={() => onLogin('administrador')} className="py-3 px-4 bg-primary-container text-on-primary-container text-xs font-bold rounded-xl hover:bg-primary hover:text-white transition-colors flex items-center justify-center gap-2">
              <span className="material-symbols-outlined text-sm">admin_panel_settings</span>
              Ingresar como Administrador (Diputado)
            </button>
            <div className="flex gap-2">
              <button onClick={() => onLogin('tecnico', tecnicoCategory)} className="flex-1 py-3 px-4 bg-secondary-container text-on-secondary-container text-xs font-bold rounded-xl hover:bg-secondary hover:text-white transition-colors flex items-center justify-center gap-2">
                <span className="material-symbols-outlined text-sm">manage_accounts</span>
                Ingresar como Técnico
              </button>
              <select 
                value={tecnicoCategory} 
                onChange={(e) => setTecnicoCategory(e.target.value as Category)}
                className="bg-surface-container-low border-none rounded-xl text-xs font-bold text-on-surface px-3 focus:ring-2 focus:ring-primary/20"
              >
                <option value="iniciativas">Iniciativas</option>
                <option value="citaciones">Citaciones</option>
                <option value="comisiones">Comisiones</option>
                <option value="fiscalizacion">Fiscalización</option>
                <option value="compromisos">Compromisos</option>
                <option value="actividades">Actividades</option>
                <option value="redes">Redes</option>
                <option value="afiliaciones">Afiliaciones</option>
              </select>
            </div>
          </div>
        </div>

        {/* Footer / Support */}
        <div className="mt-10 text-center space-y-4">
          <p className="text-on-surface-variant text-xs font-medium">
            © 2024 Civic Ethos Suite. Sistema de Gestión Pública.
          </p>
          <div className="flex items-center justify-center space-x-6">
            <a href="#" className="text-xs text-outline hover:text-on-surface transition-colors">Soporte Técnico</a>
            <span className="w-1 h-1 bg-outline-variant rounded-full"></span>
            <a href="#" className="text-xs text-outline hover:text-on-surface transition-colors">Seguridad</a>
            <span className="w-1 h-1 bg-outline-variant rounded-full"></span>
            <a href="#" className="text-xs text-outline hover:text-on-surface transition-colors">Privacidad</a>
          </div>
        </div>
      </main>
    </div>
  );
}

// BasquetSanarate/Frontend/src/views/auth/Login.vue
<template>
  <div class="min-h-screen w-full bg-surface text-on-surface font-body-md text-body-md antialiased flex items-center justify-center relative overflow-hidden py-space-2xl px-gutter-desktop">
    <!-- Ambient Court Accents -->
    <div class="absolute -top-32 -left-32 w-96 h-96 rounded-full bg-primary-container/15 blur-3xl pointer-events-none"></div>
    <div class="absolute -bottom-24 -right-24 w-80 h-80 rounded-full bg-tertiary-container/20 blur-3xl pointer-events-none"></div>

    <!-- Giant Typographic Watermark -->
    <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 select-none pointer-events-none opacity-[0.035] text-on-surface font-display-hero text-[180px] sm:text-[240px] tracking-tighter whitespace-nowrap leading-none font-bold uppercase">
      SANARATE
    </div>

    <!-- Central Card -->
    <div class="w-full max-w-[480px] relative z-10">
      <div class="bg-surface-container-lowest rounded-xl shadow-xl px-space-md sm:px-space-xl py-space-xl flex flex-col items-center text-center relative overflow-hidden">
        <!-- Court Decorative Ribbon -->
        <div class="absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r from-primary via-primary-container to-tertiary-fixed"></div>

        <!-- Official League Emblem -->
        <router-link to="/" class="mb-space-md flex items-center justify-center">
          <div class="w-16 h-16 rounded-full bg-surface-container-low flex items-center justify-center shadow-sm relative group transition-transform hover:scale-105 duration-200">
            <img :src="logoUrl" alt="Logo Liga Sanarateca" class="w-12 h-12 object-contain" />
            <span class="absolute -bottom-1 -right-1 flex h-4 w-4">
              <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
              <span class="relative inline-flex rounded-full h-4 w-4 bg-primary"></span>
            </span>
          </div>
        </router-link>

        <!-- Header Typography -->
        <div class="mb-space-sm">
          <span class="inline-flex items-center px-space-sm py-space-2xs rounded-full bg-surface-container text-on-surface-variant font-label-meta text-label-meta tracking-wider uppercase mb-space-2xs">
            Torneo Oficial 2025 • Apertura
          </span>
          <h1 class="font-headline-lg text-headline-lg sm:text-headline-xl text-on-surface uppercase tracking-tight">
            PORTAL DE GESTIÓN DEPORTIVA
          </h1>
        </div>
        <p class="font-body-sm text-body-sm text-secondary max-w-sm mb-space-lg leading-relaxed">
          Acceso para delegados de franquicia, árbitros colegiados, oficiales de mesa técnica y atletas inscritos.
        </p>

        <!-- Role Selector -->
        <div class="w-full mb-space-lg">
          <label class="block text-left font-label-pill text-label-pill text-on-surface mb-space-xs">
            Selecciona tu rol
          </label>
          <div class="grid grid-cols-3 gap-space-xs p-space-2xs bg-surface-container rounded-lg">
            <button 
              v-for="role in roles"
              :key="role.id"
              type="button"
              @click="selectedRole = role.id"
              :class="[
                'font-label-pill text-label-pill py-2.5 px-space-xs rounded-lg transition-all duration-200 flex items-center justify-center gap-1.5',
                selectedRole === role.id 
                  ? 'bg-primary-container text-on-primary-fixed shadow-sm font-semibold' 
                  : 'text-secondary hover:text-on-surface'
              ]"
            >
              <span class="material-symbols-outlined text-[16px]">{{ role.icon }}</span>
              <span class="truncate">{{ role.label }}</span>
            </button>
          </div>
        </div>

        <!-- Authentication Form -->
        <form @submit.prevent="handleLogin" class="w-full space-y-space-md text-left">
          <div class="flex flex-col space-y-space-2xs">
            <label class="font-label-pill text-label-pill text-on-surface flex justify-between items-center" for="identifier">
              <span>Correo Electrónico o DPI/CUI</span>
              <span class="font-label-meta text-label-meta text-secondary uppercase">Oficial Renap</span>
            </label>
            <div class="relative flex items-center">
              <span class="absolute left-4 text-secondary flex items-center pointer-events-none">
                <span class="material-symbols-outlined text-[20px]">person_outline</span>
              </span>
              <input 
                id="identifier"
                v-model="identifier"
                type="text" 
                required 
                placeholder="ejemplo@baloncesto.gt o 2548..."
                class="w-full pl-11 pr-4 py-3.5 bg-surface-container-low text-on-surface placeholder:text-outline font-body-md text-body-md rounded-lg outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary transition-all duration-200"
              />
            </div>
          </div>

          <div class="flex flex-col space-y-space-2xs">
            <div class="flex items-center justify-between">
              <label class="font-label-pill text-label-pill text-on-surface" for="password">Contraseña</label>
              <a href="#" class="font-label-meta text-label-meta text-primary hover:underline transition-colors">
                ¿Olvidaste tu contraseña?
              </a>
            </div>
            <div class="relative flex items-center">
              <span class="absolute left-4 text-secondary flex items-center pointer-events-none">
                <span class="material-symbols-outlined text-[20px]">lock_outline</span>
              </span>
              <input 
                id="password"
                v-model="password"
                :type="showPassword ? 'text' : 'password'"
                required 
                placeholder="••••••••••••"
                class="w-full pl-11 pr-11 py-3.5 bg-surface-container-low text-on-surface placeholder:text-outline font-body-md text-body-md rounded-lg outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary transition-all duration-200"
              />
              <button 
                type="button" 
                @click="showPassword = !showPassword"
                class="absolute right-3.5 text-secondary hover:text-on-surface p-1 rounded-full focus:outline-none transition-colors"
              >
                <span class="material-symbols-outlined text-[20px]">{{ showPassword ? 'visibility_off' : 'visibility' }}</span>
              </button>
            </div>
          </div>

          <div class="flex items-center justify-between pt-space-2xs">
            <label class="inline-flex items-center cursor-pointer select-none">
              <input v-model="rememberMe" type="checkbox" class="w-4 h-4 rounded text-primary accent-primary bg-surface-container-low cursor-pointer"/>
              <span class="ml-2 font-body-sm text-body-sm text-on-surface-variant">Mantener sesión iniciada</span>
            </label>
            <span class="inline-flex items-center gap-1 font-label-meta text-label-meta text-secondary">
              <span class="material-symbols-outlined text-[14px] text-primary">verified_user</span>
              256-bit SSL
            </span>
          </div>

          <div class="pt-space-xs">
            <button 
              type="submit"
              :disabled="loading"
              class="w-full py-4 px-6 rounded-full bg-primary-container hover:bg-primary-fixed text-on-primary-fixed font-headline-md text-headline-md tracking-wider uppercase transition-all duration-200 transform active:scale-[0.99] shadow-lg hover:shadow-xl flex items-center justify-center gap-2 group disabled:opacity-75 cursor-pointer"
            >
              <span v-if="loading" class="material-symbols-outlined animate-spin text-[22px]">progress_activity</span>
              <span>{{ loading ? 'ACCEDIENDO...' : 'INGRESAR AL SISTEMA' }}</span>
              <span v-if="!loading" class="material-symbols-outlined group-hover:translate-x-1 transition-transform">arrow_forward</span>
            </button>
          </div>
        </form>

        <div class="mt-space-lg pt-space-md w-full bg-surface-container-low/70 rounded-lg p-space-md flex flex-col gap-2">
          <p class="font-body-sm text-body-sm text-on-surface">
            ¿Tu equipo aún no está inscrito en la temporada?
          </p>
          <a href="#" class="inline-flex items-center justify-center font-label-pill text-label-pill text-primary hover:text-on-primary-container transition-colors group">
            <span>Solicitar registro de franquicia deportiva</span>
            <span class="material-symbols-outlined text-[16px] ml-1 group-hover:translate-x-0.5 transition-transform">open_in_new</span>
          </a>
        </div>
      </div>

      <div class="mt-space-md flex flex-wrap items-center justify-between text-secondary font-label-meta text-label-meta px-space-xs gap-2">
        <div class="flex items-center gap-2">
          <span class="w-2 h-2 rounded-full bg-primary"></span>
          <span>Sanarate, El Progreso • Gimnasio Municipal</span>
        </div>
        <div class="flex items-center gap-4">
          <router-link to="/" class="hover:text-on-surface transition-colors">Sitio Público</router-link>
          <span>•</span>
          <a href="#" class="hover:text-on-surface transition-colors">Soporte Técnico</a>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import logoUrl from '../../assets/images/logo.png';

const router = useRouter();

const selectedRole = ref('delegado');
const identifier = ref('');
const password = ref('');
const showPassword = ref(false);
const rememberMe = ref(true);
const loading = ref(false);

const roles = [
  { id: 'delegado', label: 'Delegado', icon: 'badge' },
  { id: 'arbitro', label: 'Oficial', icon: 'sports' },
  { id: 'jugador', label: 'Atleta', icon: 'person' }
];

const handleLogin = () => {
  loading.value = true;
  setTimeout(() => {
    loading.value = false;
    router.push('/dashboard');
  }, 800);
};
</script>
