// CoreFix/Diseno/src/components/Footer.tsx
import React from 'react';
import { 
  Wrench, 
  MapPin, 
  Mail, 
  Phone, 
  MessageSquare
} from 'lucide-react';
import { NavTab } from '../types';

interface FooterProps {
  setActiveTab: (tab: NavTab) => void;
  onOpenWhatsApp: () => void;
}

export const Footer: React.FC<FooterProps> = ({
  setActiveTab,
  onOpenWhatsApp,
}) => {
  return (
    <footer className="bg-slate-50 border-t border-slate-200/80 text-slate-700">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-14 lg:py-16">
        <div className="grid grid-cols-1 md:grid-cols-12 gap-10 lg:gap-12">
          
          {/* Column 1: Brand & Slogan */}
          <div className="md:col-span-5 lg:col-span-5 space-y-4">
            <div 
              onClick={() => { setActiveTab('inicio'); window.scrollTo({ top: 0, behavior: 'smooth' }); }}
              className="flex items-center gap-2.5 cursor-pointer inline-flex"
            >
              <div className="w-8 h-8 rounded-lg bg-blue-600 text-white flex items-center justify-center shadow-xs">
                <Wrench className="w-4 h-4 -rotate-45" />
              </div>
              <span className="text-xl font-bold tracking-tight text-slate-900">
                TechFix <span className="text-blue-600">Services</span>
              </span>
            </div>

            <p className="text-slate-600 text-sm leading-relaxed max-w-sm">
              Expertos en soluciones tecnológicas rápidas, transparentes y profesionales.
            </p>

            <div className="pt-2 text-xs text-slate-500">
              <p>Taller equipado con instrumental de laboratorio de última generación.</p>
            </div>
          </div>

          {/* Column 2: Conectar (Social / Channels) */}
          <div className="md:col-span-3 lg:col-span-3 space-y-3">
            <h4 className="text-sm font-bold text-slate-900 uppercase tracking-wider">
              Conectar
            </h4>
            <ul className="space-y-2.5 text-sm">
              <li>
                <a 
                  href="https://facebook.com" 
                  target="_blank" 
                  rel="noreferrer" 
                  className="text-slate-600 hover:text-blue-600 transition-colors"
                >
                  Facebook
                </a>
              </li>
              <li>
                <a 
                  href="https://instagram.com" 
                  target="_blank" 
                  rel="noreferrer" 
                  className="text-slate-600 hover:text-blue-600 transition-colors"
                >
                  Instagram
                </a>
              </li>
              <li>
                <button 
                  onClick={onOpenWhatsApp} 
                  className="text-slate-600 hover:text-emerald-600 transition-colors text-left cursor-pointer"
                >
                  WhatsApp
                </button>
              </li>
              <li>
                <a 
                  href="https://linkedin.com" 
                  target="_blank" 
                  rel="noreferrer" 
                  className="text-slate-600 hover:text-blue-600 transition-colors"
                >
                  LinkedIn
                </a>
              </li>
            </ul>
          </div>

          {/* Column 3: Atención al Cliente */}
          <div className="md:col-span-4 lg:col-span-4 space-y-3">
            <h4 className="text-sm font-bold text-slate-900 uppercase tracking-wider">
              Atención al Cliente
            </h4>
            
            <div className="space-y-3 text-sm text-slate-600">
              <div className="flex items-start gap-2.5">
                <MapPin className="w-4 h-4 text-slate-500 shrink-0 mt-0.5" />
                <span>Av. Tecnológica 1024, Distrito Centro</span>
              </div>

              <div className="flex items-center gap-2.5">
                <Mail className="w-4 h-4 text-slate-500 shrink-0" />
                <a href="mailto:soporte@techfix.com" className="hover:text-blue-600 transition-colors">
                  soporte@techfix.com
                </a>
              </div>

              <div className="flex items-center gap-2.5">
                <Phone className="w-4 h-4 text-slate-500 shrink-0" />
                <a href="tel:+12345678900" className="hover:text-blue-600 transition-colors font-medium text-slate-800">
                  +1 234 567 8900
                </a>
              </div>
            </div>

            <div className="pt-2">
              <span className="inline-flex items-center gap-1.5 px-3 py-1 bg-emerald-50 text-emerald-700 rounded-md text-xs font-medium border border-emerald-200">
                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                Guardia técnica para emergencias activa
              </span>
            </div>
          </div>

        </div>
      </div>

      {/* Bottom Sub-footer */}
      <div className="border-t border-slate-200 py-6 text-center text-xs text-slate-500">
        <div className="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row justify-between items-center gap-3">
          <p>© 2024 TechFix Services. Todos los derechos reservados.</p>
          <div className="flex gap-4 text-slate-500">
            <span className="hover:text-slate-700 cursor-pointer">Términos del Servicio</span>
            <span>•</span>
            <span className="hover:text-slate-700 cursor-pointer">Políticas de Garantía</span>
            <span>•</span>
            <span className="hover:text-slate-700 cursor-pointer">Privacidad de Datos</span>
          </div>
        </div>
      </div>
    </footer>
  );
};

// WEB-CYD/Frontend/src/components/Footer.vue
<script setup>
import { Facebook, Instagram, Mail, Phone, MapPin } from 'lucide-vue-next'

const scrollToSection = (id) => {
  const element = document.getElementById(id)
  if (element) {
    element.scrollIntoView({ behavior: 'smooth' })
  }
}
</script>

<template>
  <footer class="bg-gradient-to-br from-gray-900 to-gray-800 text-white pt-16 pb-8">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="grid md:grid-cols-2 lg:grid-cols-4 gap-8 mb-12">
        <!-- Logo & About -->
        <div class="space-y-4">
          <div class="flex items-center space-x-3">
            <div class="relative w-12 h-12">
              <img
                src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/document-uploads/LOGO-2020-1761860820111.png?width=100&height=100&resize=contain"
                alt="Logo CYD"
                class="absolute inset-0 object-contain w-full h-full"
              />
            </div>
            <div>
              <div class="text-lg font-bold bg-gradient-to-r from-green-400 to-yellow-400 bg-clip-text text-transparent">
                Colegio CYD
              </div>
              <div class="text-xs text-gray-400 whitespace-pre-line">Ciencia y Desarrollo</div>
            </div>
          </div>
          <p class="text-sm text-gray-400 whitespace-pre-line">
            Formando líderes con valores desde 1992. Educación de excelencia en Salama, Baja Verapaz.
          </p>
          <div class="flex space-x-3">
            <a
              href="https://facebook.com"
              target="_blank"
              rel="noopener noreferrer"
              class="w-10 h-10 rounded-full bg-white/10 hover:bg-white/20 flex items-center justify-center transition-colors"
            >
              <Facebook :size="20" />
            </a>
            <a
              href="https://instagram.com"
              target="_blank"
              rel="noopener noreferrer"
              class="w-10 h-10 rounded-full bg-white/10 hover:bg-white/20 flex items-center justify-center transition-colors"
            >
              <Instagram :size="20" />
            </a>
          </div>
        </div>

        <!-- Enlaces Rápidos -->
        <div>
          <h4 class="font-bold mb-4 text-lg">Enlaces Rápidos</h4>
          <ul class="space-y-2 text-sm">
            <li>
              <button @click="scrollToSection('inicio')" class="text-gray-400 hover:text-white transition-colors">
                Inicio
              </button>
            </li>
            <li>
              <button @click="scrollToSection('niveles')" class="text-gray-400 hover:text-white transition-colors">
                Niveles Educativos
              </button>
            </li>
            <li>
              <button @click="scrollToSection('actividades')" class="text-gray-400 hover:text-white transition-colors">
                Actividades
              </button>
            </li>
            <li>
              <button @click="scrollToSection('nosotros')" class="text-gray-400 hover:text-white transition-colors">
                Sobre Nosotros
              </button>
            </li>
            <li>
              <button @click="scrollToSection('galeria')" class="text-gray-400 hover:text-white transition-colors">
                Galería
              </button>
            </li>
            <li>
              <button @click="scrollToSection('contacto')" class="text-gray-400 hover:text-white transition-colors">
                Contacto
              </button>
            </li>
          </ul>
        </div>

        <!-- Niveles -->
        <div>
          <h4 class="font-bold mb-4 text-lg">Niveles</h4>
          <ul class="space-y-2 text-sm text-gray-400">
            <li class="hover:text-white transition-colors cursor-pointer">Preprimaria</li>
            <li class="hover:text-white transition-colors cursor-pointer">Primaria</li>
            <li class="hover:text-white transition-colors cursor-pointer">Básicos</li>
            <li class="hover:text-white transition-colors cursor-pointer">Diversificado</li>
            <li class="hover:text-white transition-colors cursor-pointer">Bachillerato en Ciencias</li>
            <li class="hover:text-white transition-colors cursor-pointer">Perito Contador</li>
          </ul>
        </div>

        <!-- Contacto -->
        <div>
          <h4 class="font-bold mb-4 text-lg">Contacto</h4>
          <ul class="space-y-3 text-sm text-gray-400">
            <li class="flex items-start space-x-3">
              <MapPin :size="18" class="mt-0.5 flex-shrink-0" />
              <span>Salama, Baja Verapaz, Guatemala</span>
            </li>
            <li class="flex items-start space-x-3">
              <Phone :size="18" class="mt-0.5 flex-shrink-0" />
              <div>
                <div>+502 1234-5678</div>
                <div>+502 9876-5432</div>
              </div>
            </li>
            <li class="flex items-start space-x-3">
              <Mail :size="18" class="mt-0.5 flex-shrink-0" />
              <div>
                <div>info@colegiocyd.edu.gt</div>
                <div>inscripciones@colegiocyd.edu.gt</div>
              </div>
            </li>
          </ul>
        </div>
      </div>

      <!-- Bottom Bar -->
      <div class="border-t border-white/10 pt-8 mt-8">
        <div class="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
          <p class="text-sm text-gray-400 text-center md:text-left">
            © {{ new Date().getFullYear() }} Colegio Particular Mixto CYD. Todos los derechos reservados.
          </p>
          <div class="flex space-x-6 text-sm text-gray-400">
            <a href="#" class="hover:text-white transition-colors">Privacidad</a>
            <a href="#" class="hover:text-white transition-colors">Términos</a>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>
